---
- name: containerd setup
  hosts: "{{ target }}"
  become: true
 
  tasks:
  - name: Update the apt packages
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Install containerd from apt
    ansible.builtin.apt:
      pkg:
      - containerd

  - name: Create the directory if it does not exist
    ansible.builtin.file:
      path: /etc/containerd
      state: directory
      mode: u=rw,g=r,o=r
  
  - name: container config
    shell: sudo containerd config default | sudo tee /etc/containerd/config.toml

  # - name: Create the file if it does not exist
  #   ansible.builtin.file:
  #     path: /etc/containerd/config.toml
  #     state: touch
  #     mode: u=rw,g=r,o=r

  # - name: Add the container d files
  #   lineinfile:
  #     dest: /etc/containerd/config.toml
  #     regexp: '.*{{ item }}$'
  #     line: "{{ item }}"
  #     state: present
  #   loop:
  #     - sudo containerd config default

  - name: restart containerd
    shell: sudo systemctl restart containerd

  - name: Disable memory swap
    shell: sudo swapoff -a