---
  - name: Include a play after another play
    import_playbook: setup.yml

  - name: Include a play after another play
    import_playbook: k3ssetup.yml

  - name: Include a play after another play
    import_playbook: containerd.yml

  - name: Include a play after another play
    import_playbook: kubecommands.yml

  - name: Include a play after another play
    import_playbook: control.yml