---
- name: K8s Controller
  hosts: all
  become: true
 
  tasks: 

  - name: Get the print join command from Control
    shell: "sudo kubeadm token create --print-join-command"
    register: join_worker_command
    when: inventory_hostname in groups['prox-k8s-control']
  - debug:
      msg: join_worker_command.stdout_lines[0]

  - name: Set the fact from control for workers
    set_fact:
      join_worker_command: "{{join_worker_command.stdout_lines[0]}}"
    when: inventory_hostname in groups['prox-k8s-control']
    
  - name: Check if host is configured
    stat:
      path: /etc/kubernetes/kubelet.conf
    register: k8s_host_configured

  - name: Join non-added hosts
    shell: "sudo {{hostvars['k8s-control'].join_worker_command}}"
    when: inventory_hostname in groups['prox-k8s-workers'] and not k8s_host_configured.stat.exists